### PR TITLE
fix notebook 5 - take 2

### PR DESCRIPTION
**Pull request by tlogan2000**
Notebook 5 broken due to new Jupyter env https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/95#issuecomment-1014962656

### CODE REVIEW

**Comment by tlvu** [comment]
Yes can test before merge, I can test for you.

**Review by tlvu — APPROVED** [review]
Fix works but let me do the merge so I sync the merge with the Jupyter env PR

**Comment by tlogan2000** [comment]
@tlvu le notebook 'forecasting hydro' semble mal converti vers html?

**Comment by tlvu** [comment]
> @tlvu le notebook 'forecasting hydro' semble mal converti vers html?

@tlogan2000 
No idea I only check if Jenkins pass against all the .ipynb files.  Not looking at html.

**Comment by tlogan2000** [comment]
> > @tlvu le notebook 'forecasting hydro' semble mal converti vers html?
> 
> @tlogan2000 No idea I only check if Jenkins pass against all the .ipynb files. Not looking at html.

ok. i'll try to see what is up

**Pull request merged**
